### PR TITLE
Add an English translation of the README

### PR DESCRIPTION
**Pull request by darthlukan**
This commit adds an English version of the README as a separate file. The translation is as close to the original Norwegian text as possible while still being as grammatically correct as possible given the format.  Words are spelled with "European English" in mind.  The purpose of this commit is to allow for a wider audience to understand the concept so as to gain as many volunteers/contributors as possible.

### CODE REVIEW

**Comment by asbjornenge** [comment]
:+1: :rocket:

**Comment by asbjornenge** [comment]
I have linked to this repo to a could of Norwegian organizations and people. So I'll keep the original README for now. But if we get traction I am positive to switch the two, and to English for the whole project.

**Comment by darthlukan** [comment]
Oh no, I don't mean to switch the Readme, I was thinking that there could be multiple versions in multiple languages so that the widest possible audiences could be comfortably reached.  Ideally, all content would be available in any language there's a translator for.

**Comment by asbjornenge** [comment]
@darthlukan nono, I know :smile: But I personally think it makes sense to switch to English as the default eventually... Thanks for the translation!

**Comment by darthlukan** [comment]
:+1:

**Pull request merged**
